Switch to api.openstreetmap.org API host
JOSM/josm pull request #132
Opened 2023-10-13 15:13 UTC by danieldegroot2

Use `api.openstreetmap.org/api/` -and HTTPS- instead of `www.openstreetmap.org/api/*`.

(Is: https://github.com/openstreetmap/operations/issues/951)

Except in validating a (manual) url, where the HTTP version has been left as valid for now.
Optionally, warn users if they are using the `www` and/or HTTP url.

Also changes some other URLs which redirect from HTTP to HTTPS into HTTPS urls.

This GitHub PR does not have a linked JOSM issue ticket at https://josm.openstreetmap.de/report .
Commit descriptions are left as default 'updated file ...'.

cc: @tsmock

2023-10-16 12:04 UTC, tsmock requested changes

2023-10-16 12:04 UTC, tsmock commented on test/unit/org/openstreetmap/josm/JOSMFixture.java
This is a test file -- it has no effect in production. Probably safe, but I do need to run the tests, even though `JOSMFixture` should be rarely used at this point.

2023-10-16 14:19 UTC, danieldegroot2 commented on test/unit/org/openstreetmap/josm/JOSMFixture.java
I can replace this PR by one with just the changes to `JOSMFixture.java` so you can start testing right away. Is this okay?
(Changes made on desktop browser version.)

2023-10-16 14:50 UTC, tsmock commented on test/unit/org/openstreetmap/josm/JOSMFixture.java
I can make the changes locally. It does take ~10 minutes for the tests to run. I'll do that as soon as I finish what I'm currently working on, if I don't see something urgent in the ticket tracker.

2023-10-16 18:32 UTC, tsmock commented on test/unit/org/openstreetmap/josm/JOSMFixture.java
The tests passed, so it looks like nothing in JOSM core needs the `www.` checks.

2023-10-18 18:42 UTC, danieldegroot2 commented on test/unit/org/openstreetmap/josm/JOSMFixture.java
Let me know what you think should be done with the PR. You can always close it. ;-)

2024-09-07 20:45 UTC, danieldegroot2 commented
Closing as redundant.

2024-09-07 20:45 UTC, closed without merging